source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed"
end

platforms :mingw, :x64_mingw, :mswin do
  gem "tzinfo-data"
  gem "wdm", "~> 0.1.0"
end
