source "https://rubygems.org"

# Ensure required stdlib gems are available on newer Rubies
gem "bigdecimal"
gem "csv"
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-include-cache"
end